### ISSUE TITLE
dotenv-action@v0.2.5 is not working when one environment variable value need to be used in another environment variable value

### ISSUE THREAD

**Issue by ashikkumar23** [falti/dotenv-action#15]
**Example**: Say, there is a `.env` file with below key/value pairs:

```
TEST_ENV=staging
BASE_URL=https://example-${TEST_ENV}.org
```
From the output, it's clear that it's not able to replace the value of `TEST_ENV` i.e., `staging` for the env variable `BASE_URL` i.e., `https://example-staging.org`

```
| loading .env file from ./tests/.env
| loaded 2 values into the environment
[Run Smoke Tests/test]   ⚙  ::set-output:: generic=please check for actual outputs
[Run Smoke Tests/test]   ⚙  ::set-output:: test_env=staging
[Run Smoke Tests/test]   ⚙  ::set-output:: base_url=https://example-${TEST_ENV}.org
```

Ideally, would expect the output to be:

```
| loading .env file from ./tests/.env
| loaded 2 values into the environment
[Run Smoke Tests/test]   ⚙  ::set-output:: generic=please check for actual outputs
[Run Smoke Tests/test]   ⚙  ::set-output:: test_env=staging
[Run Smoke Tests/test]   ⚙  ::set-output:: base_url=https://example-staging.org
```

Not sure, how to achieve this. Please advise.

**Note**: Used as below:

```
      - name: Dotenv Action
        id: dotenv
        uses: falti/dotenv-action@v0.2.5
        with:
          path: ./tests/.env
```
