### ISSUE TITLE
Value in env file is ignored if the key defines an existing environment variable

### ISSUE THREAD

**Issue by ptc-aeveritt** [falti/dotenv-action#49]
I am trying to use this action to change the value of an existing environment variable but it appears to ignore the value in the env file in this case.

For example:
Environment already has `FOO=BAR`

Create env file with `FOO=BAZ`
Add this to the workflow
```
      - name: Setup environment
        uses: falti/dotenv-action@v1.0.4
        with:
          path: global.env
          keys-case: "bypass"
          log-variables: true
          export-variables: true
```
And observe the following in the log:
```
loading .env file from global.env
{
  FOO: 'BAR'
}
```

I'm not sure whether this behaviour is by design? Would it be possible to log a warning in this case or ideally provide a flag to have the dotenv-action override the existing key value with the new one?
