### ISSUE TITLE
Add `ensure-exists` to action.yml

### ISSUE THREAD

**Issue by robbeman** [falti/dotenv-action#60]
`ensure-exists` is missing in the action.yml file, which triggers warnings while running (but it does work).

https://github.com/falti/dotenv-action/blob/7a3a44a5ef43c9a7ff7eab7deb63e355d5f5b0ef/action.yml#L6-L30

```yml
  ensure-exists:
    description: "Fail the action when .env file is not found at path."
    required: false
    default: "true"
```
