### ISSUE TITLE
define path in a directory?

### ISSUE THREAD

**Issue by spacedawwwg** [falti/dotenv-action#8]
I'm using a mono repo and I'm looking to define a path to a `.env` file in a package like so

```
- name: Load .env.development variables (Development)
  if: startsWith(github.ref, 'master') != true
  id: dotenv
  with:
    path: packages/website/.env.development
```
But no matter how I try to define the path I always get a `##[error]file does not exist` error

**Comment by spacedawwwg** [comment]
Ok. my mistake. it needs to be wrapped in `" "`
```
- name: Load .env.development variables (Development)
  if: startsWith(github.ref, 'master') != true
  id: dotenv
  with:
    path: "./packages/website/.env.development"
```
maybe worth putting an example in the readme
